### ISSUE TITLE
Add Top Instagram Influencers & Top Tik Tok Influencers to Our Footer

### ISSUE THREAD

**Issue by David-mo** [inBeat/inbeat-website#88]
Add 2 links to the footer:

Top Instagram Influencers
Top TikTok Influencers

Refer these two links to their respective page.
https://www.inbeat.co/top-influencers/instagram/
https://www.inbeat.co/top-influencers/tiktok/

**Comment by afunnydev** [comment]
We are not generating Top TikTok influencers yet, since we just have 60K in Algolia. Do you want me to generate them?

**Comment by David-mo** [comment]
Interesting point. I think the faster we go at ranking these pages, the better.

Having said that, let's wait for our Instagram pages to index, as Google doesn't seem to indexing all of them (which is why I want to add it in the footer).
On 2020-05-02 12:57:34 PM, Félix <notifications@github.com> wrote:
We are not generating Top TikTok influencers yet, since we just have 60K in Algolia. Do you want me to generate them?

**Comment by David-mo** [comment]
So we put the Tik Tok on hold.
On 2020-05-02 1:17:21 PM, David <david@inbeat.co> wrote:
Interesting point. I think the faster we go at ranking these pages, the better.

Having said that, let's wait for our Instagram pages to index, as Google doesn't seem to indexing all of them (which is why I want to add it in the footer).
On 2020-05-02 12:57:34 PM, Félix <notifications@github.com> wrote:
We are not generating Top TikTok influencers yet, since we just have 60K in Algolia. Do you want me to generate them?
